/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as TransferenciaRouteImport } from './routes/transferencia'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as SplitsRouteImport } from './routes/splits'
import { Route as SaqueRouteImport } from './routes/saque'
import { Route as PixRouteImport } from './routes/pix'
import { Route as InfracoesRouteImport } from './routes/infracoes'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as DepositoRouteImport } from './routes/deposito'
import { Route as ChavesApiRouteImport } from './routes/chaves-api'
import { Route as IndexRouteImport } from './routes/index'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferenciaRoute = TransferenciaRouteImport.update({
  id: '/transferencia',
  path: '/transferencia',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitsRoute = SplitsRouteImport.update({
  id: '/splits',
  path: '/splits',
  getParentRoute: () => rootRouteImport,
} as any)
const SaqueRoute = SaqueRouteImport.update({
  id: '/saque',
  path: '/saque',
  getParentRoute: () => rootRouteImport,
} as any)
const PixRoute = PixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const InfracoesRoute = InfracoesRouteImport.update({
  id: '/infracoes',
  path: '/infracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositoRoute = DepositoRouteImport.update({
  id: '/deposito',
  path: '/deposito',
  getParentRoute: () => rootRouteImport,
} as any)
const ChavesApiRoute = ChavesApiRouteImport.update({
  id: '/chaves-api',
  path: '/chaves-api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chaves-api': typeof ChavesApiRoute
  '/deposito': typeof DepositoRoute
  '/documentacao': typeof DocumentacaoRoute
  '/extrato': typeof ExtratoRoute
  '/infracoes': typeof InfracoesRoute
  '/pix': typeof PixRoute
  '/saque': typeof SaqueRoute
  '/splits': typeof SplitsRoute
  '/transacoes': typeof TransacoesRoute
  '/transferencia': typeof TransferenciaRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chaves-api': typeof ChavesApiRoute
  '/deposito': typeof DepositoRoute
  '/documentacao': typeof DocumentacaoRoute
  '/extrato': typeof ExtratoRoute
  '/infracoes': typeof InfracoesRoute
  '/pix': typeof PixRoute
  '/saque': typeof SaqueRoute
  '/splits': typeof SplitsRoute
  '/transacoes': typeof TransacoesRoute
  '/transferencia': typeof TransferenciaRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chaves-api': typeof ChavesApiRoute
  '/deposito': typeof DepositoRoute
  '/documentacao': typeof DocumentacaoRoute
  '/extrato': typeof ExtratoRoute
  '/infracoes': typeof InfracoesRoute
  '/pix': typeof PixRoute
  '/saque': typeof SaqueRoute
  '/splits': typeof SplitsRoute
  '/transacoes': typeof TransacoesRoute
  '/transferencia': typeof TransferenciaRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chaves-api'
    | '/deposito'
    | '/documentacao'
    | '/extrato'
    | '/infracoes'
    | '/pix'
    | '/saque'
    | '/splits'
    | '/transacoes'
    | '/transferencia'
    | '/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chaves-api'
    | '/deposito'
    | '/documentacao'
    | '/extrato'
    | '/infracoes'
    | '/pix'
    | '/saque'
    | '/splits'
    | '/transacoes'
    | '/transferencia'
    | '/webhooks'
  id:
    | '__root__'
    | '/'
    | '/chaves-api'
    | '/deposito'
    | '/documentacao'
    | '/extrato'
    | '/infracoes'
    | '/pix'
    | '/saque'
    | '/splits'
    | '/transacoes'
    | '/transferencia'
    | '/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChavesApiRoute: typeof ChavesApiRoute
  DepositoRoute: typeof DepositoRoute
  DocumentacaoRoute: typeof DocumentacaoRoute
  ExtratoRoute: typeof ExtratoRoute
  InfracoesRoute: typeof InfracoesRoute
  PixRoute: typeof PixRoute
  SaqueRoute: typeof SaqueRoute
  SplitsRoute: typeof SplitsRoute
  TransacoesRoute: typeof TransacoesRoute
  TransferenciaRoute: typeof TransferenciaRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencia': {
      id: '/transferencia'
      path: '/transferencia'
      fullPath: '/transferencia'
      preLoaderRoute: typeof TransferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splits': {
      id: '/splits'
      path: '/splits'
      fullPath: '/splits'
      preLoaderRoute: typeof SplitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saque': {
      id: '/saque'
      path: '/saque'
      fullPath: '/saque'
      preLoaderRoute: typeof SaqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix': {
      id: '/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof PixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infracoes': {
      id: '/infracoes'
      path: '/infracoes'
      fullPath: '/infracoes'
      preLoaderRoute: typeof InfracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposito': {
      id: '/deposito'
      path: '/deposito'
      fullPath: '/deposito'
      preLoaderRoute: typeof DepositoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaves-api': {
      id: '/chaves-api'
      path: '/chaves-api'
      fullPath: '/chaves-api'
      preLoaderRoute: typeof ChavesApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChavesApiRoute: ChavesApiRoute,
  DepositoRoute: DepositoRoute,
  DocumentacaoRoute: DocumentacaoRoute,
  ExtratoRoute: ExtratoRoute,
  InfracoesRoute: InfracoesRoute,
  PixRoute: PixRoute,
  SaqueRoute: SaqueRoute,
  SplitsRoute: SplitsRoute,
  TransacoesRoute: TransacoesRoute,
  TransferenciaRoute: TransferenciaRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
